
github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-modeling
      branch: master
    - name: activiti-cloud-acceptance-scenarios
      branch: master
      useSinglePullRequest: true
    - name: activiti-cloud-full-chart
      useSinglePullRequest: true  
